name: pkg-pr-new

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build package
        run: pnpm build

      - name: Debug workspace info
        run: |
          echo "Workspace packages:"
          pnpm list --depth=-1 --json
          echo "Package directories:"
          find packages -name "package.json" | head -10

      - name: Publish preview packages
        run: pnpm dlx pkg-pr-new publish './packages/*'


